#Variables
JAVA_FILES = clsCoder.java clsCustomComp.java clsMain.java clsReader.java clsStringDisplay.java clsWriter.java
EXE = clsMain

#Commands
compile:
	javac $(JAVA_FILES)
run:
	java $(EXE)
clean:
	rm *.class

