#Variables
JAVA_FILES = BrickBreaker_Ball.java BrickBreaker_Brick.java BrickBreaker_Paddle.java clsGame_BrickBreaker.java
EXE = clsGame_BrickBreaker

#Commands
compile:
	javac $(JAVA_FILES)
run:
	java $(EXE)
clean:
	rm *.class

